id: I41666FB9
default_language: zh
source: https://www2.hf.uio.no/polyglotta/index.php?page=library&bid=2
initial_creation_type: input
imported: 2023-02-09 14:45:08.485773
last_modified: 2023-02-09 14:45:08.485906
source_metadata:
  title: 'PP: Aṣṭasāhasrikā Prajñāpāramitā'
  language: zh
bases:
  38BC:
    base_file: 38BC.txt
    order: 1
copyright:
  status: Unknown
  notice: ''
